### ISSUE TITLE
Barong email hangs after dropping conn to db on docker swarm

### ISSUE THREAD

**Issue by sundanny26** [openware/barong#1068]
barong version: https://github.com/openware/barong/tree/2.4.1
image: "quay.io/openware/barong:2.4.1"

This seems to be the main problem. when I deploy the service of barong email in docker swarm, after a while the service seems to disconnect from other services like database and rabbitmq:

Mysql
```
{"level":"ERROR","time":"2020-05-11 22:26:04 +0000","message":"#<ActiveRecord::StatementInvalid: Mysql2::Error::ConnectionError: Lost connection to MySQL server during query: SELECT  `users`.* FROM `users` WHERE `users`.`uid` = 'ID....' LIMIT 1>"}
{"level":"ERROR","time":"2020-05-12 12:25:13 +0000","message":"#<Mysql2::Error: MySQL client is not connected>"}
```
RabbitMQ
```
[info] <0.4292.3> accepting AMQP connection <0.4292.3> (10.0.1.4:49960 -> 10.0.1.96:5672)
[info] <0.4292.3> connection <0.4292.3> (10.0.1.4:49960 -> 10.0.1.96:5672): user 'test' authenticated and granted access to vhost '/'
[warning] <0.3649.3> closing AMQP connection <0.3649.3> (10.0.1.4:43702 -> 10.0.1.96:5672, vhost: '/', user: 'test'):
client unexpectedly closed TCP connection
```

It will work for a while and after 30 minutes or so it will get stuck in there and send no more emails, database disconnects.

In the same swarm I have deployed barong and peatio, and both are behaving normally when connecting to database or AMQP. So far it looks like a problem in swarm connections, but in this `barong_email` service is not controlling this kind of error. So that's why it going to just break over and over again until you restart the server either manually or terminating the process. On the contrary when deployed in docker-compose connection keeps stable.

To recover connection to database I need to restart the script `/bin/mailer`. When I have it good for a while

Here I post the error on the database side:
```
2020-05-11T16:06:53.630787Z 36 [Note] Aborted connection 36 to db: 'barong_production' user: 'test' host: 'host' (Got an error reading communication packets)
```

Here I have how the `barong_email` is configured in the daemons
```
  barong_email:
    restart: always
    image: "quay.io/openware/barong:2.4.1"
    env_file:
      - ../config/barong.env
    volumes:
      - ../config/barong/views:/home/app/app/views
      - ../config/barong/mailer.yml:/home/app/config/mailer.yml
    entrypoint: [ "./bin/mailer", "--config=config/mailer.yml", "run" ]
```
