### ISSUE TITLE
undefined method `megabytes

### ISSUE THREAD

**Issue by ImanMousavi** [openware/barong#1079]
```
{
"level":"ERROR","time":"2020-05-23 18:14:15 +0000",
"message":"**undefined method `megabytes' for** nil:NilClass\n/home/app/app/uploaders/upload_uploader.rb:25:in 
`size_range'\n/home/app/vendor/bundle/ruby/2.6.0/gems/carrierwave-2.0.2/lib/carrierwave/uploader/file_size.rb:31:in 
`check_size!'\n/home/app/vendor/bundle/ruby/2.6.0/gems/carrierwave-
2.0.2/lib/carrierwave/uploader/callbacks.rb:14:in `block in 
with_callbacks'\n/home/app/vendor/bundle/ruby/2.6.0/gems/carrierwave-
2.0.2/lib/carrierwave/uploader/callbacks.rb:14:in 
`each'\n/home/app/vendor/bundle/ruby/2.6.0/gems/carrierwave-
2.0.2/lib/carrierwave/uploader/callbacks.rb:14:in 
`with_callbacks'\n/home/app/vendor/bundle/ruby/2.6.0/gems/carrierwave-
2.0.2/lib/carrierwave/uploader/cache.rb:144:in `cache!'"
}
```
My ENV is:
```
storage:
  provider: "local"
  bucketName: "local"
  region: fra1
  endpoint: https://fra1.digitaloceanspaces.com
  accessKey: "changeme"
  secretKey: "changeme"
  signatureVersion: "2"
```
