### ISSUE TITLE
Getting duplicate emails being sent for every template

### ISSUE THREAD

**Issue by leocape** [openware/barong#1176]
Using Barong 2.5x - tried 2.5.1 -> 2.5.17 get the same result for each version.

Each email that is sent will be sent twice immediately

**mailer logs:**
`"level":"INFO","time":"2020-11-11 21:12:46 +0000","message":"Listening for events."}
{"level":"DEBUG","time":"2020-11-11 21:12:54 +0000","message":"  \u001b[1m\u001b[35m (0.6ms)\u001b[0m  \u001b[1m\u001b[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES')
, ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483\u001b[0m"}
{"level":"DEBUG","time":"2020-11-11 21:12:55 +0000","message":"  \u001b[1m\u001b[36mUser Load (0.7ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  `users`.* FROM `users` WHERE `users`.`uid` = 'ID2375964C3C' LIMIT 1\
u001b[0m"}
{"level":"DEBUG","time":"2020-11-11 21:12:55 +0000","message":"  \u001b[1m\u001b[36mProfile Load (0.7ms)\u001b[0m  \u001b[1m\u001b[34mSELECT `profiles`.* FROM `profiles` WHERE `profiles`.`user_id` = 46\u001b
[0m"}
{"level":"INFO","time":"2020-11-11 21:12:55 +0000","message":"  Rendering postmaster/session_create.en.html.erb within layouts/mailer"}
{"level":"INFO","time":"2020-11-11 21:12:55 +0000","message":"  Rendered postmaster/session_create.en.html.erb within layouts/mailer (4.2ms)"}
{"level":"DEBUG","time":"2020-11-11 21:12:55 +0000","message":"Postmaster#process_payload: processed outbound mail in 16.8ms"}
{"level":"INFO","time":"2020-11-11 21:12:55 +0000","message":"Sent mail to email@domain.com (204.2ms)"}`
email template html continues ->

**Mailer.yml**
```
keychain:
  barong:
    algorithm: RS256
    value: "<%= @barong_public_key %>"
  peatio:
    algorithm: RS256
    value: "<%= @barong_public_key %>"

exchanges:
  barong_system:
    name: barong.events.system
    signer: barong
  barong_model:
    name: barong.events.model
    signer: barong
  peatio:
    name: peatio.events.model
    signer: peatio

events:
  - name: Email Confirmation
    key: user.email.confirmation.token
    exchange: barong_system
    templates:
      EN:
        subject: Registration Confirmation
        template_path: email_confirmation.en.html.erb
      ru:
        subject: Подтверждение Регистрации
        template_path: email_confirmation.ru.html.erb

  - name: Password Reset
    key: user.password.reset.token
    exchange: barong_system
    templates:
      EN:
        subject: Password Reset
        template_path: password_reset.en.html.erb
      ru:
        subject: Сброс Пароля
        template_path: password_reset.ru.html.erb

  - name: Label Created
    key: label.created
    exchange: barong_model
    templates:
      EN:
        subject: Your account has been fully verified
        template_path: label.en.html.erb

  - name: Session Create
    key: session.create
    exchange: barong_system
    templates:
      EN:
        subject: New Login
        template_path: session_create.en.html.erb

  - name: Deposit Accepted
    key: deposit.updated
    exchange: peatio
    templates:
      EN:
        subject: Deposit Accepted
        template_path: deposit_accepted.en.html.erb

  - name: Withdrawal Succeed
    key: withdraw.updated
    exchange: peatio
    templates:
      EN:
        subject: Withdrawal Succeed
        template_path: withdraw_succeed.en.html.erb

  - name: New Beneficiary
    key: beneficiary.created
    exchange: peatio
    templates:
      EN:
        subject: New Beneficiary
        template_path: new_beneficiary.en.html.erb
```
